### ISSUE TITLE
Best practices for automatic dependencies...

### ISSUE THREAD

**Issue by wtanksleyjr** [gfxmonk/gup#8]
This is not a bug report, or a complaint... More of an advanced question that I'm being forced to think about as I propose my company switch to gup.

Many people have worked on forcing /make/ to handle C header files; a set of best practices has developed (see link at the end for an example). Could you give some suggestions for handling generated dependency lists like those produced by GCC's -MMD switch (which is what my company uses) or X's makedepends?

I'm not so much asking about how to process the .d files generated by -MMD; that's not hard -- each .d file contains a single make rule, with the object file depending on a single .c file and the header files included from it; if the resulting list gets long it's broken apart by backslash continuations. That might be a good use case for Python!

Rather, I'm asking how I should best handle dependencies that come from inside intermediate files, and may in theory appear and disappear arbitrarily (when the C files, and sometimes when the H files, are edited; or if the user deletes one of the .d files or renames a single C file therefore making its .d file no longer be present).

http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/

**Comment by gfxmonk** [comment]
Hmm, I may be a little rusty on gcc's dependency files (haven't used them for a while myself), but this seems like it should be a fairly straightforward task for gup. Unlike `make`, gup doesn't need dependency information before it builds - it can produce this as a side effect of a build target, which is conveniently how -MDD works already.

So I'd imagine you'd build with gcc normally, and just tell gup about the intermediate dependencies after you've compiled. Something like:

	# Gupfile:
	gup-compile-obj:
		*.o

	# gup-compile-obj:
	#!bash
	mkdir -p deps
	base="$(basename "$2" .o)"
	dep_dest="deps/$base.d"
	gup -u "$base.c"
	gcc -MDD -MF "$dep_dest" -o "$1" "$base.c"
	gup -u "$dep_dest" # only really necessary if you something else could change the .d file
	./gup-process-depends "$dep_dest"
	# if you write the build script in python, you can just
	# make this a function call rather than a subprocess

	# gup-process-depends:
	#/usr/bin/env python
	def parse_dependencies(filename):
		# TODO
		pass
	for dependency in parse_dependencies(sys.argv[1])
		subprocess.check_call(['gup', '-u', dependency])
	
The one thing that this might miss is if intermediate dependencies are themselves generated - e.g. foo.c includes bar.h, but bar.h is actually a gup target. In such a case, you'd end up compiling with the _old_ version of foo.c, and only after you've compiled you'd be getting gup to update bar.h. If that can happen in your project, you'd either:

 - explicitly `gup -u <generated headers>` in `gup-compile-obj` before you do the compilation (if there's just one or two generated headers), or
 - do the dependency stuff before the actual compilation, like so:

	gcc -MD -MF "$dep_dest" "$base.c"
	gup -u "$dep_dest"
	./gup-process-depends "$dep_dest"
	gcc -o "$1" "$base.c"

(in this case, the `*.d` files could be separate gup target themselves, rather than just a side-effect of building the `*.o`)

Please let me know if there's some point I've missed - as I said, I haven't used gcc's dependency generation stuff in a while myself.

**Comment by wtanksleyjr** [comment]
I'll have to experiment, but I find your answer very plausible and clear -- unlike what's needed for makefiles.

I hesitate to close this, since it's really good information, but I think you've answered my question well.

**Comment by gfxmonk** [comment]
Since this is mainly a discussion more than a particular, are you happy if I post this correspondence to the [mailing list](https://groups.google.com/forum/#!forum/gup-users) for posterity and then close this issue?

**Comment by wtanksleyjr** [comment]
Thank you, yes. I didn't know that list was active -- I'll prefer it in the
future for similar things.

**Comment by gfxmonk** [comment]
Cool - it's certainly not _very_ active, but it's probably the best place for such things :)
